services:
  puppeteer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puppeteer-microservice
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"
    networks:
      - puppeteer-network
    volumes:
      - /tmp:/tmp:rw
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb

  # Optional: Add Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: puppeteer-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - puppeteer-service
    networks:
      - puppeteer-network
    profiles:
      - production

networks:
  puppeteer-network:
    driver: bridge
